import { getDb, dbRun } from './db.js';

await getDb();

const docs = [
  { id: crypto.randomUUID(), title: 'Getting Started with Home Growth OS', tier: 'system', category: 'onboarding', status: 'active', effective_date: '2024-01-01', content: 'Home Growth OS is your all-in-one platform for managing residential property growth.\n\nKey Modules:\n- Portfolio Dashboard: View all properties, occupancy rates, and revenue\n- Tenant Management: Track leases, communications, and maintenance requests\n- Financial Reporting: Automate rent collection and expense tracking\n- Compliance Center: Stay on top of inspections and legal requirements\n\nFirst Steps:\n1. Add your first property under Portfolio > Add Property\n2. Upload lease agreements to Documents\n3. Invite team members under Settings > Team\n4. Set up rent reminders under Tenant > Automation' },
  { id: crypto.randomUUID(), title: 'How to Run Financial Reports', tier: 'system', category: 'tutorials', status: 'active', effective_date: '2024-01-01', content: 'Running Financial Reports\n\nMonthly Report:\n1. Go to Financials > Reports\n2. Select Profit and Loss from the dropdown\n3. Choose your date range\n4. Click Generate to download\n\nRent Roll Report:\n- Navigate to Tenants > Rent Roll\n- Filter by property or view all\n- Export to CSV for your accountant' },
  { id: crypto.randomUUID(), title: 'Setting Up Maintenance Workflows', tier: 'system', category: 'tutorials', status: 'active', effective_date: '2024-01-01', content: 'Maintenance Workflows\n\nPriority Levels:\n- Emergency 24hr: No heat, flooding, gas leaks, security issues\n- Urgent 72hr: Appliance failure, hot water out, HVAC\n- Routine 14 days: Cosmetic repairs, minor fixes\n- Scheduled: Preventive maintenance' },
  { id: crypto.randomUUID(), title: 'California AB 1482 Rent Control Limits', tier: 'industry', category: 'rent_control', jurisdiction: 'CA', status: 'active', effective_date: '2020-01-01', content: 'California AB 1482 Tenant Protection Act\n\nRent Increase Limits:\nAnnual rent increases are capped at 5 percent plus local CPI, not to exceed 10 percent total.\n\nCovered Properties:\n- Multi-family buildings 15 or more years old\n- Single-family homes unless owner provides exemption notice\n\nJust Cause for Eviction: Required after 12 months of tenancy.\n\nSource: California Civil Code Section 1947.12' },
  { id: crypto.randomUUID(), title: 'Federal Fair Housing Act Anti-Discrimination', tier: 'industry', category: 'fair_housing', jurisdiction: 'federal', status: 'active', effective_date: '1968-04-11', content: 'Fair Housing Act Federal Requirements\n\nProtected Classes: Race, Color, National origin, Religion, Sex, Familial status, Disability\n\nProhibited: Refusing to rent, different terms, falsely claiming unit unavailable\n\nPenalties: Up to $21,663 for first violation, $108,315 for subsequent.' },
  { id: crypto.randomUUID(), title: 'Security Deposit Rules California 2024', tier: 'industry', category: 'deposits', jurisdiction: 'CA', status: 'active', effective_date: '2024-07-01', content: 'California Security Deposit Rules AB 12 Effective July 1 2024\n\nDeposits now capped at 1 months rent. Previously 2 months unfurnished, 3 months furnished.\n\nReturn Timeline: 21 days after tenant vacates.\n\nSource: California Civil Code 1950.5 amended by AB 12 2023' },
  { id: crypto.randomUUID(), title: 'Security Deposit California PRE-2024 RETIRED', tier: 'industry', category: 'deposits', jurisdiction: 'CA', status: 'retired', effective_date: '2005-01-01', expiry_date: '2024-06-30', content: 'RETIRED: Old California Security Deposit Rules\n\nTHIS RULE IS RETIRED as of July 1 2024.\n\nOld limit was 2 months unfurnished, 3 months furnished. Now replaced by AB 12 1-month cap.' },
  { id: crypto.randomUUID(), title: 'Habitability Standards All States', tier: 'industry', category: 'habitability', jurisdiction: 'federal', status: 'active', effective_date: '2000-01-01', content: 'Implied Warranty of Habitability\n\nRequired:\n- Weatherproofing: Keep out rain and wind\n- Plumbing: Hot and cold water, working toilets\n- Heating: Maintain 68 degrees Fahrenheit\n- Electrical: Safe wiring and outlets\n- Pest-free at move-in' }
];

dbRun('DELETE FROM knowledge_docs');
for (const doc of docs) {
  dbRun('INSERT INTO knowledge_docs (id,title,content,tier,category,jurisdiction,client_id,status,effective_date,expiry_date,version) VALUES (?,?,?,?,?,?,?,?,?,?,?)',
    [doc.id,doc.title,doc.content,doc.tier,doc.category||null,doc.jurisdiction||null,doc.client_id||null,doc.status,doc.effective_date||null,doc.expiry_date||null,1]);
}
console.log('Seeded ' + docs.length + ' documents successfully');
